photography_site/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from photography_site import settings
from photography_site.views import home_page, about_page

urlpatterns = [
    path('', home_page, name="Home"),
    path('', include('site_gallery.urls', namespace='CategoryUrls')),
    path('', include('site_contact.urls', namespace='Contact_Us')),
    path('', include('site_service.urls', namespace='Services')),
    path('about-us', about_page, name="About-us"),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    # add root static files!
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files!
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_contact/urls.py
from django.urls import path

from site_contact.views import contact_page

app_name = 'Contact_Us'

urlpatterns = [
    path('contact-us', contact_page, name='contact')
]

site_service/urls.py
from django.urls import path

from site_service.views import services_page

app_name = 'Services'

urlpatterns = [
    path('services', services_page, name='services')
]

templates/shared/Footer.html
{% load static %}

<div class="footer py-4">
    <div class="container-fluid text-center">
        <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright ©
            <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
            <script>document.write(new Date().getFullYear());</script>
            2021 All rights reserved | This template is made with <i class="icon-heart-o" aria-hidden="true"></i> by <a
                href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
    </div>
</div>

templates/shared/FooterRef.html
{% load static %}


<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'js/swiper.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/picturefill.min.js' %}"></script>
<script src="{% static 'js/lightgallery-all.min.js' %}"></script>
<script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/mediaelement-and-player.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#lightgallery').lightGallery();
    });
</script>

templates/shared/Header.html
{% load static %}
{% url "Home" as home_url %}
{% url "About-us" as about_url %}
{% url 'Contact_Us:contact' as ContactUs_url %}
{% url 'Services:services' as services_url %}

<div class="site-mobile-menu">
    <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
        </div>
    </div>
    <div class="site-mobile-menu-body">
        <ul class="site-nav-wrap">
            <li class="active"><a href="/">Home</a></li>
            <li class="has-children"><span class="arrow-collapse collapsed" data-toggle="collapse"
                                           data-target="#collapseItem0"></span>
                <a href="#">Gallery</a>
                <ul class="collapse" id="collapseItem0">
                    {% for category in categories %}
                        <li><a href="/category/{{ category.name }}">{{ category.name }}</a></li>
                    {% endfor %}
                    <li class="has-children"><span class="arrow-collapse collapsed" data-toggle="collapse"
                                                   data-target="#collapseItem1"></span>
                        <a href="#">Sub Menu</a>
                        <ul class="collapse" id="collapseItem1">
                            <li><a href="#">Menu One</a></li>
                            <li><a href="#">Menu Two</a></li>
                            <li><a href="#">Menu Three</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="{{ services_url }}">Services</a></li>
            <li><a href="{{ about_url }}">About</a></li>
            <li><a href="{{ ContactUs_url }}">Contact</a></li>
        </ul>
        <ul class="site-nav-wrap" data-class="social">
            <li>
                <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
            </li>
            <li>
                <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
            </li>
            <li>
                <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            </li>
            <li>
                <a href="#" class="pl-3 pr-3"><span class="icon-youtube-play"></span></a>
            </li>
        </ul>
    </div>
</div>

<header class="site-navbar py-3" role="banner">

    <div class="container-fluid">
        <div class="row align-items-center">

            <div class="col-6 col-xl-2 aos-init aos-animate" data-aos="fade-down">
                <h1 class="mb-0"><a href="/" class="text-white h2 mb-0">{{ settings.site_title }}</a></h1>
            </div>
            <div class="col-10 col-md-8 d-none d-xl-block aos-init aos-animate" data-aos="fade-down">
                <nav class="site-navigation position-relative text-right text-lg-center" role="navigation">

                    <ul class="site-menu js-clone-nav mx-auto d-none d-lg-block">
                        <li class="{% if request.path == home_url %}active{% endif %}"><a href="/">Home</a></li>
                        <li class="has-children">
                            <a href="#">Gallery</a>
                            <ul class="dropdown">
                                {% for category in categories %}
                                    <li><a href="/category/{{ category.name }}">{{ category.name }}</a></li>
                                {% endfor %}
                                <li class="has-children">
                                    <a href="#">Sub Menu</a>
                                    <ul class="dropdown">
                                        <li><a href="#">Menu One</a></li>
                                        <li><a href="#">Menu Two</a></li>
                                        <li><a href="#">Menu Three</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="{% if request.path == services_url %}active{% endif %}"><a
                                href="{{ services_url }}">Services</a>
                        </li>
                        <li class="{% if request.path == about_url %}active{% endif %}"><a
                                href="{{ about_url }}">About</a></li>
                        <li class="{% if request.path == ContactUs_url %}active{% endif %}"><a
                                href="{{ ContactUs_url }}">Contact</a>
                        </li>
                    </ul>
                </nav>
            </div>

            <div class="col-6 col-xl-2 text-right aos-init aos-animate" data-aos="fade-down">
                <div class="d-none d-xl-inline-block">
                    <ul class="site-menu js-clone-nav ml-auto list-unstyled d-flex text-right mb-0" data-class="social">
                        <li>
                            <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                        </li>
                        <li>
                            <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                        </li>
                        <li>
                            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                        </li>
                        <li>
                            <a href="#" class="pl-3 pr-3"><span class="icon-youtube-play"></span></a>
                        </li>
                    </ul>
                </div>

                <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" style="position: relative; top: 3px;"><a
                        href="#" class="site-menu-toggle js-menu-toggle text-black"><span
                        class="icon-menu h3"></span></a></div>

            </div>

        </div>
    </div>

</header>

templates/shared/HeaderRef.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
<link rel="stylesheet" href="{% static 'css/mediaelementplayer.css' %}">
<link rel="stylesheet" href="{% static 'css/lightgallery.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&amp;family=Roboto+Mono:wght@400;700&amp;display=swap"
      rel="stylesheet">
<link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/lightgallery.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
<link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'css/swiper.css' %}">
<link rel="stylesheet" href="{% static 'css/aos.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/shared/_MainLayout.html
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include "shared/HeaderRef.html" %}
</head>

<body data-aos-easing="slide" data-aos-duration="800" data-aos-delay="0">
<div class="site-wrap">
    {% render_partial "photography_site.views.header" %}
    {% block content %}{% endblock content %}
    {% render_partial "photography_site.views.footer" %}
    {% include "shared/FooterRef.html" %}
</div>
</body>
</html>